version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKSTACK_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELKSTACK_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic

  logstash:
    container_name: logstash
    build:
      context: ./logstash
      args:
        ELKSTACK_VERSION=${ELKSTACK_VERSION}
    ports:
      - 51514:51514
    volumes:
      - logstash_pipelines:/usr/share/logstash/pipeline/
    networks:
      - elastic

volumes:
  data01:
    driver: local
  logstash_pipelines:
    driver: local

networks:
  elastic:
    driver: bridge